stages:
  load_data:
    cmd: python src/stage_01_load_data.py
    deps:
      - src/stage_01_load_data.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
  
  save_data:
    cmd: python src/stage_02_split_data.py
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/raw_local_dir/data.csv
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/test.csv
      - artifacts/split_data_dir/train.csv

  train:
    cmd: python src/stage_03_train.py
    deps:
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
    params:
      - base.random_state
      - model_params.RandomForest.params.n_jobs
      - model_params.RandomForest.params.max_depth
      - model_params.RandomForest.params.n_estimators
      - model_params.RandomForest.params.oob_score
    outs:
      - artifacts/model_dir/saved_model

  evaluate:
    cmd: python src/stage_04_evaluate.py
    deps:
      - src/stage_04_evaluate.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model_dir/saved_model
    outs:
      - artifacts/scores_dir/scores.json