
data_source: "BankNote_Authentication.csv"

artifacts: 
  artifacts_dir: artifacts
  raw_local_dir:  raw_local_dir
  raw_local_file:  data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv

  model_dir: model_dir
  model_filename: saved_model.model

  scores_dir: scores_dir
  scores_filename: scores.json